services:
  plane-redis:
    image: valkey/valkey:7.2.11-alpine
    restart: unless-stopped
    networks:
      - dev_env
    volumes:
      - redisdata:/data
    ports:
      - "17379:6379"

  plane-mq:
    image: rabbitmq:3.13.6-management-alpine
    restart: unless-stopped
    networks:
      - dev_env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}

  plane-minio:
    image: minio/minio
    restart: unless-stopped
    networks:
      - dev_env
    entrypoint: >
      /bin/sh -c "
      mkdir -p /export/${AWS_S3_BUCKET_NAME} &&
      minio server /export --console-address ':9090' &
      sleep 5 &&
      mc alias set myminio http://localhost:9000 ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY} &&
      mc mb myminio/${AWS_S3_BUCKET_NAME} -p || true
      && tail -f /dev/null
      "
    volumes:
      - uploads:/export
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "17900:9000"
      - "17990:9090"

  plane-db:
    image: postgres:15.7-alpine
    restart: unless-stopped
    networks:
      - dev_env
    command: postgres -c 'max_connections=1000'
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data
    ports:
      - "17432:5432"

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile.dev
      args:
        DOCKER_BUILDKIT: 1
    restart: unless-stopped
    networks:
      - dev_env
    volumes:
      - ./apps/api:/code
    command: ./bin/docker-entrypoint-api-local.sh
    env_file:
      - ./apps/api/.env
    depends_on:
      - plane-db
      - plane-redis
      - plane-mq
    ports:
      - "17000:8000"

  worker:
    build:
      context: ./apps/api
      dockerfile: Dockerfile.dev
      args:
        DOCKER_BUILDKIT: 1
    restart: unless-stopped
    networks:
      - dev_env
    volumes:
      - ./apps/api:/code
    command: ./bin/docker-entrypoint-worker.sh
    env_file:
      - ./apps/api/.env
    depends_on:
      - api
      - plane-db
      - plane-redis

  beat-worker:
    build:
      context: ./apps/api
      dockerfile: Dockerfile.dev
      args:
        DOCKER_BUILDKIT: 1
    restart: unless-stopped
    networks:
      - dev_env
    volumes:
      - ./apps/api:/code
    command: ./bin/docker-entrypoint-beat.sh
    env_file:
      - ./apps/api/.env
    depends_on:
      - api
      - plane-db
      - plane-redis

  migrator:
    build:
      context: ./apps/api
      dockerfile: Dockerfile.dev
      args:
        DOCKER_BUILDKIT: 1
    restart: "no"
    networks:
      - dev_env
    volumes:
      - ./apps/api:/code
    command: ./bin/docker-entrypoint-migrator.sh --settings=plane.settings.local
    env_file:
      - ./apps/api/.env
    depends_on:
      - plane-db
      - plane-redis

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.dev
    restart: unless-stopped
    networks:
      - dev_env
    volumes:
      - ./apps:/app/apps
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/packages/codemods/node_modules
      - /app/packages/constants/node_modules
      - /app/packages/decorators/node_modules
      - /app/packages/editor/node_modules
      - /app/packages/hooks/node_modules
      - /app/packages/i18n/node_modules
      - /app/packages/logger/node_modules
      - /app/packages/propel/node_modules
      - /app/packages/services/node_modules
      - /app/packages/shared-state/node_modules
      - /app/packages/tailwind-config/node_modules
      - /app/packages/types/node_modules
      - /app/packages/typescript-config/node_modules
      - /app/packages/ui/node_modules
      - /app/packages/utils/node_modules
    env_file:
      - ./apps/web/.env
    depends_on:
      - api
    ports:
      - "17300:17300"

  admin:
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile.dev
    restart: unless-stopped
    networks:
      - dev_env
    volumes:
      - ./apps:/app/apps
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/admin/node_modules
      - /app/packages/codemods/node_modules
      - /app/packages/constants/node_modules
      - /app/packages/decorators/node_modules
      - /app/packages/editor/node_modules
      - /app/packages/hooks/node_modules
      - /app/packages/i18n/node_modules
      - /app/packages/logger/node_modules
      - /app/packages/propel/node_modules
      - /app/packages/services/node_modules
      - /app/packages/shared-state/node_modules
      - /app/packages/tailwind-config/node_modules
      - /app/packages/types/node_modules
      - /app/packages/typescript-config/node_modules
      - /app/packages/ui/node_modules
      - /app/packages/utils/node_modules
    env_file:
      - ./apps/admin/.env
    depends_on:
      - api
    ports:
      - "17301:17301"

  space:
    build:
      context: .
      dockerfile: ./apps/space/Dockerfile.dev
    restart: unless-stopped
    networks:
      - dev_env
    volumes:
      - ./apps:/app/apps
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/space/node_modules
      - /app/packages/codemods/node_modules
      - /app/packages/constants/node_modules
      - /app/packages/decorators/node_modules
      - /app/packages/editor/node_modules
      - /app/packages/hooks/node_modules
      - /app/packages/i18n/node_modules
      - /app/packages/logger/node_modules
      - /app/packages/propel/node_modules
      - /app/packages/services/node_modules
      - /app/packages/shared-state/node_modules
      - /app/packages/tailwind-config/node_modules
      - /app/packages/types/node_modules
      - /app/packages/typescript-config/node_modules
      - /app/packages/ui/node_modules
      - /app/packages/utils/node_modules
    env_file:
      - ./apps/space/.env
    depends_on:
      - api
    ports:
      - "17302:17302"

  live:
    build:
      context: .
      dockerfile: ./apps/live/Dockerfile.dev
    restart: unless-stopped
    networks:
      - dev_env
    volumes:
      - ./apps:/app/apps
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/live/node_modules
      - /app/packages/codemods/node_modules
      - /app/packages/constants/node_modules
      - /app/packages/decorators/node_modules
      - /app/packages/editor/node_modules
      - /app/packages/hooks/node_modules
      - /app/packages/i18n/node_modules
      - /app/packages/logger/node_modules
      - /app/packages/propel/node_modules
      - /app/packages/services/node_modules
      - /app/packages/shared-state/node_modules
      - /app/packages/tailwind-config/node_modules
      - /app/packages/types/node_modules
      - /app/packages/typescript-config/node_modules
      - /app/packages/ui/node_modules
      - /app/packages/utils/node_modules
    env_file:
      - ./apps/live/.env
    environment:
      API_BASE_URL: "http://api:8000"
      REDIS_HOST: "plane-redis"
      REDIS_PORT: "6379"
      REDIS_URL: "redis://plane-redis:6379/"
    depends_on:
      - api
      - plane-redis
    ports:
      - "17310:17310"

volumes:
  redisdata:
  uploads:
  pgdata:
  rabbitmq_data:

networks:
  dev_env:
    driver: bridge
