FROM node:22-alpine

RUN apk add --no-cache libc6-compat
WORKDIR /app

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

COPY . .
RUN corepack enable pnpm && pnpm add -g turbo
RUN pnpm install
EXPOSE 17310

ENV TURBO_TELEMETRY_DISABLED=1

VOLUME [ "/app/node_modules", "/app/live/node_modules"]

CMD ["pnpm","dev", "--filter=live"]
